# Generated by Django 4.2.1 on 2023-07-03 16:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('size', models.FloatField(null=True)),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
    ]
