# Generated by Django 4.2.1 on 2023-06-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('price', models.CharField(max_length=30, null=True)),
                ('discount_price', models.CharField(max_length=30, null=True)),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=15, null=True)),
                ('size', models.CharField(max_length=5, null=True)),
                ('count', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
